# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Boammani Aser Lompo
email: lompoaser9@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi there! I'm Aser, a recent Master's graduate specializing in Large Language Models.
  I'm passionate about Machine Learning and excited to share my experiences, insights, and projects with you on this site!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AserLompo
github_username:  aser97
fixed_navbar: top

social:
  instagram: https://www.instagram.com/aserlompo?igsh=MXBhbDBkZHR3YWtraQ%3D%3D&utm_source=qr
  tiktok: https://www.tiktok.com/@aserlompo?_t=ZM-8uQwpcplb30&_r=1
  x: https://x.com/aserlompo?s=21&t=QQJKjGRJo6l8wfFOZcKGPg
  

# Build settings
theme: bulma-clean-theme
permalink: pretty

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
